/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as HouseRulesRouteImport } from './routes/house-rules'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CancellationRouteImport } from './routes/cancellation'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApartmentsRouteImport } from './routes/apartments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminHousekeepingRouteImport } from './routes/_authenticated/admin.housekeeping'
import { Route as AuthenticatedAdminGuestsRouteImport } from './routes/_authenticated/admin.guests'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedAdminApartmentsRouteImport } from './routes/_authenticated/admin.apartments'
import { Route as AuthenticatedAccountBookingIdRouteImport } from './routes/_authenticated/account.$bookingId'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseRulesRoute = HouseRulesRouteImport.update({
  id: '/house-rules',
  path: '/house-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CancellationRoute = CancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsRoute = ApartmentsRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHousekeepingRoute =
  AuthenticatedAdminHousekeepingRouteImport.update({
    id: '/housekeeping',
    path: '/housekeeping',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGuestsRoute =
  AuthenticatedAdminGuestsRouteImport.update({
    id: '/guests',
    path: '/guests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApartmentsRoute =
  AuthenticatedAdminApartmentsRouteImport.update({
    id: '/apartments',
    path: '/apartments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountBookingIdRoute =
  AuthenticatedAccountBookingIdRouteImport.update({
    id: '/$bookingId',
    path: '/$bookingId',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/house-rules': typeof HouseRulesRoute
  '/nearby': typeof NearbyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/account/$bookingId': typeof AuthenticatedAccountBookingIdRoute
  '/admin/apartments': typeof AuthenticatedAdminApartmentsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/guests': typeof AuthenticatedAdminGuestsRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/house-rules': typeof HouseRulesRoute
  '/nearby': typeof NearbyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/account/$bookingId': typeof AuthenticatedAccountBookingIdRoute
  '/admin/apartments': typeof AuthenticatedAdminApartmentsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/guests': typeof AuthenticatedAdminGuestsRoute
  '/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/apartments': typeof ApartmentsRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/cancellation': typeof CancellationRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/house-rules': typeof HouseRulesRoute
  '/nearby': typeof NearbyRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/account/$bookingId': typeof AuthenticatedAccountBookingIdRoute
  '/_authenticated/admin/apartments': typeof AuthenticatedAdminApartmentsRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/guests': typeof AuthenticatedAdminGuestsRoute
  '/_authenticated/admin/housekeeping': typeof AuthenticatedAdminHousekeepingRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apartments'
    | '/auth'
    | '/book'
    | '/cancellation'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/gallery'
    | '/house-rules'
    | '/nearby'
    | '/privacy'
    | '/terms'
    | '/why-choose-us'
    | '/account'
    | '/admin'
    | '/account/$bookingId'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/guests'
    | '/admin/housekeeping'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apartments'
    | '/auth'
    | '/book'
    | '/cancellation'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/gallery'
    | '/house-rules'
    | '/nearby'
    | '/privacy'
    | '/terms'
    | '/why-choose-us'
    | '/account'
    | '/account/$bookingId'
    | '/admin/apartments'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/guests'
    | '/admin/housekeeping'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/apartments'
    | '/auth'
    | '/book'
    | '/cancellation'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/gallery'
    | '/house-rules'
    | '/nearby'
    | '/privacy'
    | '/terms'
    | '/why-choose-us'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/account/$bookingId'
    | '/_authenticated/admin/apartments'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/guests'
    | '/_authenticated/admin/housekeeping'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApartmentsRoute: typeof ApartmentsRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  CancellationRoute: typeof CancellationRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  HouseRulesRoute: typeof HouseRulesRoute
  NearbyRoute: typeof NearbyRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-rules': {
      id: '/house-rules'
      path: '/house-rules'
      fullPath: '/house-rules'
      preLoaderRoute: typeof HouseRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancellation': {
      id: '/cancellation'
      path: '/cancellation'
      fullPath: '/cancellation'
      preLoaderRoute: typeof CancellationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartments': {
      id: '/apartments'
      path: '/apartments'
      fullPath: '/apartments'
      preLoaderRoute: typeof ApartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/housekeeping': {
      id: '/_authenticated/admin/housekeeping'
      path: '/housekeeping'
      fullPath: '/admin/housekeeping'
      preLoaderRoute: typeof AuthenticatedAdminHousekeepingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/guests': {
      id: '/_authenticated/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AuthenticatedAdminGuestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/apartments': {
      id: '/_authenticated/admin/apartments'
      path: '/apartments'
      fullPath: '/admin/apartments'
      preLoaderRoute: typeof AuthenticatedAdminApartmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/$bookingId': {
      id: '/_authenticated/account/$bookingId'
      path: '/$bookingId'
      fullPath: '/account/$bookingId'
      preLoaderRoute: typeof AuthenticatedAccountBookingIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountBookingIdRoute: typeof AuthenticatedAccountBookingIdRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountBookingIdRoute: AuthenticatedAccountBookingIdRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApartmentsRoute: typeof AuthenticatedAdminApartmentsRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminGuestsRoute: typeof AuthenticatedAdminGuestsRoute
  AuthenticatedAdminHousekeepingRoute: typeof AuthenticatedAdminHousekeepingRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApartmentsRoute: AuthenticatedAdminApartmentsRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminGuestsRoute: AuthenticatedAdminGuestsRoute,
  AuthenticatedAdminHousekeepingRoute: AuthenticatedAdminHousekeepingRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ApartmentsRoute: ApartmentsRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  CancellationRoute: CancellationRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  HouseRulesRoute: HouseRulesRoute,
  NearbyRoute: NearbyRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
